apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: clusters.ezekiel20.online
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://taskapp-ezekiel-kops-state/clusters.ezekiel20.online
  dnsZone: clusters.ezekiel20.online
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-eu-west-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.35.3
  masterPublicName: api.clusters.ezekiel20.online
  networkCIDR: 10.0.0.0/16
  networkID: vpc-012b130a81350b79e
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://taskapp-ezekiel-kops-state/clusters.ezekiel20.online/discovery
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.0.101.0/24
    id: subnet-031390d9954634d4a
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - cidr: 10.0.102.0/24
    id: subnet-084bae3da21ede1ec
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - cidr: 10.0.103.0/24
    id: subnet-037f789f4ab8045c7
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - cidr: 10.0.1.0/24
    id: subnet-0fe7656c7c1df4846
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - cidr: 10.0.2.0/24
    id: subnet-003b7c641af103508
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - cidr: 10.0.3.0/24
    id: subnet-0757bfcf52f6f1d3b
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
  topology:
    bastion:
      bastionPublicName: bastion.clusters.ezekiel20.online
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: control-plane-eu-west-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: control-plane-eu-west-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: control-plane-eu-west-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: nodes-eu-west-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3a.medium
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - eu-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: nodes-eu-west-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3a.medium
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - eu-west-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: nodes-eu-west-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3a.medium
  maxPrice: "0.025"
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: bastions
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  role: Bastion
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  labels:
    kops.k8s.io/cluster: clusters.ezekiel20.online
  name: admin
spec:
  publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGLRPBJToniRY0TWwMcPgFlhMlthZy3I+ni2nt5gs2+qx6CFD1EmKkVmT+f5FxLh65qihOOfi02qgJfLUohjDoTp3lmcK2rthFi1PH72Olo7SqdMULAwuIQ5Hzq55zSIG9y5zlk+jWpO/t+gaZCAXCrt7K6F7Zlg5Be2gaVGsnvjDeY3np64z9nbhQgMfvXN9fBeRz/jN0KV/n3eM/y5wbQCC105Ap7Sfg+OlgHTml2BvEHf+Zv68JvEZMvG6O+hwSG2gkqH75hgRqR+YSd9I9pvZu6Pu1b1OXKQ3uYy6fWmzwm4IvRuhk6+yopKvSuUM6f4m3Q9EkKV5p9NtscYHhsjLARN7DIyoyKG5dhSziaSLjQatRhCAY33+06Trbr1tla5djFso4t6uX924FCRQyF6DUaexLkrHvMWe7gNlyVM+XZf1UJAG5dqCEwy7IGULkNYxVG8RC4s+r48+ln42wU1YM6Ia1ktbwdRPlgQhxANruYxWkE6bbvbN5q8seP1eE2uD1JtxksRCMIRtkdA3XsokxODaapCnSuihVy6rKAvNCU/vUdyJpf2N/qM4VTvAUyU2Weu6AQb0Sl1K83xH+A2UKZ3HwyZvGNfHdbfFDnNaZLDQnXhbVUCRlvTszEIXpHqbSfkyZII1QhV1RU+Cy04AauS8Ha2MzBsSg+lqinw==
    ezekiel@ubuntu
