apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "project/capstone/database_credentials"
        objectType: "secretsmanager"
        jmesPath:
            - path: "DATABASE_HOST"
              objectAlias: "DB_HOST"
            - path: "DATABASE_PORT"
              objectAlias: "DB_PORT"
            - path: "DATABASE_NAME"
              objectAlias: "DB_NAME"
            - path: "DATABASE_PASSWORD"
              objectAlias: "DB_PASS"
            - path: "DATABASE_USER"
              objectAlias: "DB_USER"
  secretObjects:
    - secretName: db-k8s-secret
      type: Opaque
      data:
        - objectName: "DB_HOST"     # This MUST match the objectAlias above
          key: DATABASE_HOST       # This is what your Flask app sees
        - objectName: "DB_PORT"
          key: DATABASE_PORT
        - objectName: "DB_NAME"
          key: DATABASE_NAME
        - objectName: "DB_PASS"
          key: DATABASE_PASSWORD
        - objectName: "DB_USER"
          key: DATABASE_USER
