apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-service-account
  namespace: default
  annotations:
    # REPLACE this with the actual ARN of the IAM Role you created in Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/kops-db-secret-role
